spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
    password: pgpwd4habr
    username: postgres
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8081
